branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# ØKP4 CØSMOS proto"
  - - "@semantic-release/npm"
    - npmPublish: false
      tarballDir: "false"
      pkgRoot: ./ts
  - - "@google/semantic-release-replace-plugin"
    - replacements:
        - files:
            - python/cosmos_sdk_grpc_client/pyproject.toml
            - python/okp4_grpc_client/pyproject.toml
          from: ^version = ".+"
          to: version = "${nextRelease.version}"
          countMatches: true
          results:
            - file: python/cosmos_sdk_grpc_client/pyproject.toml
              hasChanged: true
              numMatches: 1
              numReplacements: 1
            - file: python/okp4_grpc_client/pyproject.toml
              hasChanged: true
              numMatches: 1
              numReplacements: 1
        - files:
            - rust/cosmos-sdk-grpc-client/Cargo.toml
            - rust/okp4-grpc-client/Cargo.toml
          from: ^version = ".+"
          to: version = "${nextRelease.version}"
          countMatches: true
          results:
            - file: rust/cosmos-sdk-grpc-client/Cargo.toml
              hasChanged: true
              numMatches: 1
              numReplacements: 1
            - file: rust/okp4-grpc-client/Cargo.toml
              hasChanged: true
              numMatches: 1
              numReplacements: 1
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - ts/package.json
        - python/pyproject.toml
        - rust/cosmos-sdk-grpc-client/Cargo.toml
        - rust/okp4-grpc-client/Cargo.toml
      message: "chore(release): perform release ${nextRelease.version}"
